name: shop_cart_pk
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev











version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  carousel_pro: ^1.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
   - images/c1.jpg
   - images/m1.jpeg
   - images/m2.jpg
   - images/w1.jpeg
   - images/w4.jpeg
   - images/cats/tshirt.png
   - images/cats/dress.png
   - images/cats/formal.png
   - images/cats/informal.png
   - images/cats/jeans.png
   - images/cats/shoe.png
   - images/products/blazer1.jpeg
   - images/products/dress1.jpeg
   - images/products/blazer2.jpeg
   - images/products/dress2.jpeg
   - images/products/hills1.jpeg
   - images/products/hills2.jpeg
   - images/products/pants1.jpg
   - images/products/pants2.jpeg
   - images/products/shoe1.jpg
   - images/products/skt1.jpeg
   - images/products/skt2.jpeg
   